## Bài tập 1


Câu hỏi 1: a

In [38]:
import numpy as np
arr = np . arange (0 , 10 , 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
import numpy as np
arr = np . arange (1 , 10 , 1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [40]:
import numpy as np
arr = np . arange (0 , 9 , 1)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [41]:
import numpy as np
arr = np . arange (1 , 11 , 1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Câu hỏi 2: d

In [42]:
arr = np . ones ((3 ,3) ) > 0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [43]:
arr = np . ones ((3 ,3) , dtype = bool )
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [44]:
arr = np . full ((3 ,3) , fill_value = True , dtype = bool )
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Câu hỏi 3: a

In [45]:
import numpy as np
arr = np . arange (0 ,10)
print ( arr [ arr %2 == 1])

[1 3 5 7 9]


Câu hỏi 4: b

In [46]:
import numpy as np
arr = np . arange (0 ,10)
arr [ arr %2 ==1] = -1
print ( arr )

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Câu hỏi 5: b

In [47]:
import numpy as np
arr = np . arange (10)
arr_2d = arr . reshape (2 , -1)
print ( arr_2d )

[[0 1 2 3 4]
 [5 6 7 8 9]]


Câu hỏi 6: a

In [48]:
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Câu hỏi 7: c

In [49]:
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print ("C = ", c )

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Câu hỏi 8: a

In [50]:
import numpy as np
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


Câu hỏi 9: c

In [51]:
import numpy as np
a = np . array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np . where ((a >=5) &( a <=10) )
print (" result ", a [ index ])

 result  [ 6  9 10]


Câu hỏi 10: d

In [52]:
import numpy as np

def maxx (x , y ) :
    if x >= y :
        return x
    else :
        return y

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np . vectorize ( maxx , otypes =[ float ])
print ( pair_max (a , b ) )

[6. 7. 9. 8. 9. 7. 5.]


Câu hỏi 11: a

In [53]:
import numpy as np

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print (" Result ", np . where (a <b , b , a ) )

 Result  [6 7 9 8 9 7 5]


##  BÀI TẬP 2: XỬ LÝ ẢNH


Câu hỏi 12: a

In [54]:
!pip install matplotlib

In [55]:
import matplotlib.image as mpimg
img = mpimg.imread('dog.jpeg')
def rgb_to_lightness(rgb_image):
    return (np.max(rgb_image, axis=2) + np.min(rgb_image, axis=2)) / 2

gray_img_01 = rgb_to_lightness(img)
gray_img_01 [0 , 0]

102.5

Câu 13: a

In [56]:
import matplotlib.image as mpimg

img = mpimg.imread('dog.jpeg')
gray_img_02 = np.mean(img, axis=2)

print(gray_img_02[0, 0])

107.66666666666667


Câu 14: c

In [58]:
import matplotlib.image as mpimg
img = mpimg.imread('dog.jpeg')

gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
print(gray_img_03[0, 0])

126.22999999999999


## BÀI TẬP 3: Phân tích dữ liệu dạng bảng

In [61]:
!pip install pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB 435.7 kB/s eta 0:00:27
   ---------------------------------------- 0.0/11.6 MB 393.8 kB/s eta 0:00:30
   ---------------------------------------- 0.0/11.6 MB 393.8 kB/s eta 0:00:30
   ---------------------------------------- 0.0/11.6 MB 393.8 kB/s eta 0:00:30
   ---------------------------------------- 0.1/11.6 MB 218.8 kB/s eta 0:00:53
   ---------------------------------------- 0.1/11.6 MB 270.5 kB/s eta 0:00:43
   ---------------------------------------- 0.1/11.6 MB 262.6 kB/s eta 0:00:44
   ---------------------------------------- 0.1/11.6 MB 285.2 kB/s eta 0:00:41
   ---------------------------------------- 0.1/11.6 MB 285.2 kB/s eta 0:00:41
   ---------------------------------------- 0.1/11.6 MB 240.2 kB/s eta 0:00:48
   ---------------------------------------- 0.1/11.6 MB 266.2 kB/s eta

 Câu hỏi 15: c

In [62]:
import pandas as pd

df = pd.read_csv('advertising.csv')

data = df.to_numpy()

sales_column = data[:, 3]

max_value = sales_column.max()
max_index = sales_column.argmax()

print(f"Max: {max_value} - Index: {max_index}")


Max: 27.0 - Index: 175


 Câu hỏi 16:b

In [70]:
average_tv = df['TV'].mean()
print(average_tv)

147.0425


 Câu hỏi 17: a

In [69]:
count_sales_20 = df[df['Sales'] >= 20].shape[0]
print(count_sales_20)

40


Câu hỏi 18: b

In [68]:
average_radio_sales_15 = df[df['Sales'] >= 15]['Radio'].mean()
print(average_radio_sales_15)

26.22293577981651


Câu hỏi 19: c

In [67]:
average_newspaper = df['Newspaper'].mean()
total_sales_newspaper = df[df['Newspaper'] > average_newspaper]['Sales'].sum()
print(total_sales_newspaper)

1405.1


Câu hỏi 20: c

In [71]:
A = df['Sales'].mean()

# Tạo ra mảng scores
scores = []
for value in df['Sales']:
    if value > A:
        scores.append('Good')
    elif value < A:
        scores.append('Bad')
    else:
        scores.append('Average')

# In ra kết quả scores[7:10]
print(scores[7:10])

['Bad', 'Bad', 'Good']


Câu hỏi 21: c

In [72]:
closest_to_A = df['Sales'].iloc[(df['Sales'] - A).abs().argmin()]

# Tạo ra mảng scores
scores_closest = []
for value in df['Sales']:
    if value > closest_to_A:
        scores_closest.append('Good')
    elif value < closest_to_A:
        scores_closest.append('Bad')
    else:
        scores_closest.append('Average')

# In ra kết quả scores_closest[7:10]
print(scores_closest[7:10])

['Bad', 'Bad', 'Good']
